name: Playwright Tests
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**/*.md'
      - '**/ci.yml'
permissions:
      contents: 'write'
      id-token: 'write'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test && true
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: |
            playwright-report/
            allure-results/
          retention-days: 30
          
      - name: Get test results history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - name: Test marketplace action
        uses: PavanMudigonda/html-reporter-github-pages@v1.0
        id: test-report
        with:
          test_results: playwright-report
          gh_pages: gh-pages
          results_history: results-history
      - name: Publish Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_branch: gh-pages
          publish_dir: results-history
          keep_files: true 
      # - name: GH Pages Push
      #   uses: PavanMudigonda/html-reporter-github-pages/composite@v1.1
      #   with:
      #     test_results: test-results
      #     keep_reports: 20
